language: php
php:
    - 7.0
    - 7.1

branches:
    only:
        - master

matrix:
    include:
        - php: 7.0
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 7.1
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

before_script:
    - mv $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini $HOME/xdebug.ini || return 0
    - composer global require hirak/prestissimo
    - composer update --prefer-dist --dev $COMPOSER_FLAGS

script:
    - bin/php-cs-fixer --diff --dry-run -v fix
    - bin/phpspec run -fpretty
